# -*- coding: utf-8 -*-
"""Machine Learning: Prediksi Data dengan Metode Regresi dan Kuadrat

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s_wqacN-8qRAA2jdQ1auF03dMiL8f77h
"""

import numpy as np
from sklearn.linear_model import LinearRegression

# x=data, y=target
x = [[5], [10], [15], [20], [25], [30], [35], [40], [45], [50]]
y = [10, 15, 20, 25, 30, 35, 40, 45, 50, 55]

regr = LinearRegression().fit(x,y)
regr.score(x,y)

#data uji
predict = np.array([[200]])

#menampilkan data prediksi
print("Prediksi")
print("Input =", predict)
print("Output =", regr.predict(predict))

from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
import numpy as np

#Database
# x = data, y = target
x = [[5], [10], [15], [20], [25], [30], [35], [40], [45], [50]]
y = [25, 100, 225, 400, 625, 900, 1225, 1600, 2025, 2500]

#Data uji
predict = np.array([[200]])
poly = PolynomialFeatures(degree=2)
x_= poly.fit_transform(x)
predict_= poly.fit_transform(predict)
regr = linear_model.LinearRegression()
regr.fit(x_,y)

#Menmapilkan data prediksi
print ("Prediksi")
print ("Input = ", predict)
print ("Output = ", regr.predict(predict_))